server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/supportBot
    username: postgres
    password: 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: nova_support_bot
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
    show-sql: true




telegram:
  botName: '@insurance_on_bot'
  token: '5545574868:AAFjT0MeHGZPvxS_QSFQFHzYgorJT2dYdgE'