POST localhost:8082/api/v1/operator
Content-Type: application/json
Authorization: BearereyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBZG1pbiIsImlhdCI6MTY2MTI1MDE0NiwiZXhwIjoxNjYxMjU3MzQ2fQ.JPOsaqFXbbg8PqWtVCWpvdpE3aq2x652ffNv_6Pc4Bc
{
  "name": "karimxon2",
  "phoneNumber": "998946099785"
}

###
GET localhost:8082/api/v1/operator/1

###
PUT localhost:8082/api/v1/operator/1
Content-Type: application/json

{
  "phoneNumber": "50031"
}

###

GET localhost:8082/api/v1/operator/list


###

#DELETE localhost:8082/api/v1/operator/1
POST localhost:8082/api/v1/auth/login
Content-Type: application/json

{
  "username":"Admin",
  "password": 12345
}

PUT localhost:8082/api/vi/user/1
Content-Type: application/json

{
  "fullName" : "Xudoyberdi",
  "state": "START"
}