POST localhost:8082/api/v1/operator
Content-Type: application/json

{
  "name": "karimxon1",
  "phoneNumber": "998946099784"
}

###
GET localhost:8082/api/v1/operator/1

###
PUT localhost:8082/api/v1/operator/1
Content-Type: application/json

{
  "phoneNumber": "50031"
}

###

GET localhost:8082/api/v1/operator/list


###

DELETE localhost:8082/api/v1/operator/1
###
GET localhost:8082/api/vi/user/queue
###
GET localhost:8082/api/vi/user/1
###

PUT localhost:8082/api/vi/user/1
Content-Type: application/json

{
  "fullName" : "Xudoyberdi",
  "state": "START"
}